---

- name: Create TSSC Install Package
  gather_facts: false
  hosts: 127.0.0.1
  vars:
    package_dir: "{{ playbook_dir }}/package"
    image_dir: "{{ package_dir }}/container_images"
  tasks:

    - name: Download TSSC Python Package
      git:
        repo: 'https://github.com/rhtconsulting/tssc-python-package.git'
        dest: ./package/git-repos/tssc-python-package
        version: master
        remote: upstream

    - name: Download TSSC Jenkins Library
      git:
        repo: 'https://github.com/rhtconsulting/tssc-jenkins-library.git'
        dest: ./package/git-repos/tssc-jenkins-library
        version: master
        remote: upstream

    - name: Download TSSC Quarkus Reference App
      git:
        repo: 'http://gitea.tssc.rht-set.com/tssc-references/tssc-reference-app-quarkus-rest-json.git'
        dest: ./package/git-repos/tssc-reference-app-quarkus-rest-json
        version: master
        remote: upstream

    - name: Download TSSC Quarkus Reference App Configuration
      git:
        repo: 'http://gitea.tssc.rht-set.com/tssc-references/tssc-reference-app-quarkus-rest-json-config.git'
        dest: ./package/git-repos/tssc-reference-app-quarkus-rest-json-config
        version: master
        remote: upstream

    - name: Download TSSC Quarkus Reference App Maven Dependencies
      shell:
        cmd: mvn -Dmaven.repo.local=../../maven-repository dependency:go-offline
        chdir: ./package/git-repos/tssc-reference-app-quarkus-rest-json

    - name: Create Download Directory for Container Images
      file:
        path: "{{ image_dir }}"
        state: directory
        mode: '0755'

    - name: Download Jenkins Worker Container Images - Base
      shell:
        cmd: skopeo copy docker://quay.io/tssc/tssc-ci-agent-jenkins:v0.10 oci://{{ image_dir }}/tssc-ci-agent-jenkins:v0.10

    - name: Download Jenkins Worker Container Images - Maven
      shell:
        cmd: skopeo copy docker://quay.io/tssc/tssc-tool-maven:v0.10 oci://{{ image_dir }}/tssc-tool-maven:v0.10

    - name: Download Jenkins Worker Container Images - Buildah
      shell:
        cmd: skopeo copy docker://quay.io/tssc/tssc-tool-buildah:v0.10 oci://{{ image_dir }}/tssc-tool-buildah:v0.10

    - name: Download Jenkins Worker Container Images - ArgoCD
      shell:
        cmd: skopeo copy docker://quay.io/tssc/tssc-tool-argocd:v0.10 oci://{{ image_dir }}/tssc-tool-argocd:v0.10

    - name: Download Jenkins Worker Container Images - Skopeo
      shell:
        cmd: skopeo copy docker://quay.io/tssc/tssc-tool-skopeo:v0.10 oci://{{ image_dir }}/tssc-tool-skopeo:v0.10

    - name: Download Jenkins Worker Container Images - Sonar
      shell:
        cmd: skopeo copy docker://quay.io/tssc/tssc-tool-sonar:v0.10 oci://{{ image_dir }}/tssc-tool-sonar:v0.10
